import type { Timezone } from '~/types'

export const useTimezones = () => {
  const timezones: Timezone[] = [
    {
      value: 'America/New_York',
      label: 'New York',
      flag: '🇺🇸',
      country: 'USA (EST/EDT)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'nueva york',
        'ny',
        'manhattan',
        'este',
      ],
    },
    {
      value: 'America/Chicago',
      label: 'Chicago',
      flag: '🇺🇸',
      country: 'USA (CST/CDT)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'central',
        'illinois',
      ],
    },
    {
      value: 'America/Denver',
      label: 'Denver',
      flag: '🇺🇸',
      country: 'USA (MST/MDT)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'colorado',
        'montaña',
        'montana',
        'mountain',
      ],
    },
    {
      value: 'America/Los_Angeles',
      label: 'Los Angeles',
      flag: '🇺🇸',
      country: 'USA (PST/PDT)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'california',
        'la',
        'hollywood',
        'oeste',
        'pacifico',
        'pacific',
      ],
    },
    {
      value: 'America/Anchorage',
      label: 'Alaska',
      flag: '🇺🇸',
      country: 'USA (AKST/AKDT)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'alaska',
        'anchorage',
      ],
    },
    {
      value: 'Pacific/Honolulu',
      label: 'Hawaii',
      flag: '🇺🇸',
      country: 'USA (HST)',
      searchTerms: [
        'estados unidos',
        'eeuu',
        'usa',
        'united states',
        'america',
        'hawái',
        'hawaii',
        'honolulu',
        'pacifico',
        'pacific',
      ],
    },
    {
      value: 'America/Toronto',
      label: 'Toronto',
      flag: '🇨🇦',
      country: 'Canada (EST/EDT)',
      searchTerms: ['canadá', 'canada', 'ontario', 'este', 'east'],
    },
    {
      value: 'America/Vancouver',
      label: 'Vancouver',
      flag: '🇨🇦',
      country: 'Canada (PST/PDT)',
      searchTerms: [
        'canadá',
        'canada',
        'british columbia',
        'columbia británica',
        'britanica',
        'oeste',
        'pacifico',
        'pacific',
      ],
    },
    {
      value: 'America/Mexico_City',
      label: 'Mexico City',
      flag: '🇲🇽',
      country: 'Mexico (CST)',
      searchTerms: [
        'méxico',
        'mexico',
        'ciudad de méxico',
        'ciudad de mexico',
        'cdmx',
        'df',
        'capital',
      ],
    },
    {
      value: 'America/Cancun',
      label: 'Cancún',
      flag: '🇲🇽',
      country: 'Mexico (EST)',
      searchTerms: ['méxico', 'mexico', 'cancun', 'quintana roo', 'caribe', 'caribbean', 'playa'],
    },
    {
      value: 'America/Guatemala',
      label: 'Guatemala',
      flag: '🇬🇹',
      country: 'Guatemala (CST)',
      searchTerms: ['centroamérica', 'centroamerica', 'central america', 'guatemalteco'],
    },
    {
      value: 'America/Costa_Rica',
      label: 'Costa Rica',
      flag: '🇨🇷',
      country: 'Costa Rica (CST)',
      searchTerms: [
        'centroamérica',
        'centroamerica',
        'central america',
        'costarricense',
        'san jose',
        'san josé',
      ],
    },
    {
      value: 'America/Panama',
      label: 'Panama',
      flag: '🇵🇦',
      country: 'Panama (EST)',
      searchTerms: [
        'panamá',
        'centroamérica',
        'centroamerica',
        'central america',
        'panameño',
        'panameno',
      ],
    },
    {
      value: 'America/Bogota',
      label: 'Bogotá',
      flag: '🇨🇴',
      country: 'Colombia (COT)',
      searchTerms: [
        'bogota',
        'colombia',
        'colombiano',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Lima',
      label: 'Lima',
      flag: '🇵🇪',
      country: 'Peru (PET)',
      searchTerms: [
        'perú',
        'peru',
        'peruano',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Santiago',
      label: 'Santiago',
      flag: '🇨🇱',
      country: 'Chile (CLT)',
      searchTerms: ['chile', 'chileno', 'sudamérica', 'sudamerica', 'south america', 'suramerica'],
    },
    {
      value: 'America/Caracas',
      label: 'Caracas',
      flag: '🇻🇪',
      country: 'Venezuela (VET)',
      searchTerms: [
        'venezuela',
        'venezolano',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/La_Paz',
      label: 'La Paz',
      flag: '🇧🇴',
      country: 'Bolivia (BOT)',
      searchTerms: [
        'bolivia',
        'boliviano',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Guayaquil',
      label: 'Quito',
      flag: '🇪🇨',
      country: 'Ecuador (ECT)',
      searchTerms: [
        'ecuador',
        'ecuatoriano',
        'guayaquil',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Asuncion',
      label: 'Asunción',
      flag: '🇵🇾',
      country: 'Paraguay (PYT)',
      searchTerms: [
        'asuncion',
        'paraguay',
        'paraguayo',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Montevideo',
      label: 'Montevideo',
      flag: '🇺🇾',
      country: 'Uruguay (UYT)',
      searchTerms: [
        'uruguay',
        'uruguayo',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
      ],
    },
    {
      value: 'America/Sao_Paulo',
      label: 'São Paulo',
      flag: '🇧🇷',
      country: 'Brazil (BRT)',
      searchTerms: [
        'brasil',
        'brazil',
        'brasileño',
        'brasileno',
        'brazilian',
        'sao paulo',
        'san pablo',
        'sudamérica',
        'sudamerica',
        'south america',
      ],
    },
    {
      value: 'America/Buenos_Aires',
      label: 'Buenos Aires',
      flag: '🇦🇷',
      country: 'Argentina (ART)',
      searchTerms: [
        'argentina',
        'argentino',
        'sudamérica',
        'sudamerica',
        'south america',
        'suramerica',
        'ba',
      ],
    },
    {
      value: 'Europe/London',
      label: 'London',
      flag: '🇬🇧',
      country: 'UK (GMT/BST)',
      searchTerms: [
        'reino unido',
        'united kingdom',
        'inglaterra',
        'england',
        'londres',
        'gran bretaña',
        'gran bretana',
        'great britain',
        'uk',
        'gb',
        'british',
        'britanico',
      ],
    },
    {
      value: 'Europe/Paris',
      label: 'Paris',
      flag: '🇫🇷',
      country: 'France (CET)',
      searchTerms: ['francia', 'france', 'parís', 'french', 'francés', 'frances'],
    },
    {
      value: 'Europe/Berlin',
      label: 'Berlin',
      flag: '🇩🇪',
      country: 'Germany (CET)',
      searchTerms: ['alemania', 'germany', 'berlín', 'german', 'alemán', 'aleman', 'deutschland'],
    },
    {
      value: 'Europe/Madrid',
      label: 'Madrid',
      flag: '🇪🇸',
      country: 'Spain (CET)',
      searchTerms: [
        'españa',
        'spain',
        'espana',
        'español',
        'espanol',
        'spanish',
        'iberia',
        'castellano',
      ],
    },
    {
      value: 'Europe/Rome',
      label: 'Rome',
      flag: '🇮🇹',
      country: 'Italy (CET)',
      searchTerms: ['italia', 'italy', 'roma', 'italian', 'italiano'],
    },
    {
      value: 'Europe/Amsterdam',
      label: 'Amsterdam',
      flag: '🇳🇱',
      country: 'Netherlands (CET)',
      searchTerms: [
        'países bajos',
        'paises bajos',
        'holanda',
        'holland',
        'netherlands',
        'dutch',
        'holandés',
        'holandes',
      ],
    },
    {
      value: 'Europe/Brussels',
      label: 'Brussels',
      flag: '🇧🇪',
      country: 'Belgium (CET)',
      searchTerms: [
        'bélgica',
        'belgica',
        'belgium',
        'bruselas',
        'belgian',
        'belga',
        'flandes',
        'flemish',
      ],
    },
    {
      value: 'Europe/Lisbon',
      label: 'Lisbon',
      flag: '🇵🇹',
      country: 'Portugal (WET)',
      searchTerms: ['portugal', 'lisboa', 'portuguese', 'portugués', 'portugues', 'iberia'],
    },
    {
      value: 'Europe/Zurich',
      label: 'Zurich',
      flag: '🇨🇭',
      country: 'Switzerland (CET)',
      searchTerms: ['suiza', 'switzerland', 'zürich', 'zurich', 'swiss', 'suizo', 'helvetia'],
    },
    {
      value: 'Europe/Vienna',
      label: 'Vienna',
      flag: '🇦🇹',
      country: 'Austria (CET)',
      searchTerms: ['austria', 'viena', 'austrian', 'austriaco'],
    },
    {
      value: 'Europe/Stockholm',
      label: 'Stockholm',
      flag: '🇸🇪',
      country: 'Sweden (CET)',
      searchTerms: [
        'suecia',
        'sweden',
        'estocolmo',
        'swedish',
        'sueco',
        'scandinavia',
        'escandinavia',
      ],
    },
    {
      value: 'Europe/Oslo',
      label: 'Oslo',
      flag: '🇳🇴',
      country: 'Norway (CET)',
      searchTerms: ['noruega', 'norway', 'norwegian', 'noruego', 'scandinavia', 'escandinavia'],
    },
    {
      value: 'Europe/Copenhagen',
      label: 'Copenhagen',
      flag: '🇩🇰',
      country: 'Denmark (CET)',
      searchTerms: [
        'dinamarca',
        'denmark',
        'copenhague',
        'danish',
        'danés',
        'danes',
        'scandinavia',
        'escandinavia',
      ],
    },
    {
      value: 'Europe/Helsinki',
      label: 'Helsinki',
      flag: '🇫🇮',
      country: 'Finland (EET)',
      searchTerms: [
        'finlandia',
        'finland',
        'finnish',
        'finlandés',
        'finlandes',
        'scandinavia',
        'escandinavia',
      ],
    },
    {
      value: 'Europe/Warsaw',
      label: 'Warsaw',
      flag: '🇵🇱',
      country: 'Poland (CET)',
      searchTerms: ['polonia', 'poland', 'varsovia', 'polish', 'polaco'],
    },
    {
      value: 'Europe/Prague',
      label: 'Prague',
      flag: '🇨🇿',
      country: 'Czech Republic (CET)',
      searchTerms: ['república checa', 'republica checa', 'czech', 'praga', 'checo', 'chequia'],
    },
    {
      value: 'Europe/Athens',
      label: 'Athens',
      flag: '🇬🇷',
      country: 'Greece (EET)',
      searchTerms: ['grecia', 'greece', 'atenas', 'greek', 'griego', 'hellas', 'hellenic'],
    },
    {
      value: 'Europe/Istanbul',
      label: 'Istanbul',
      flag: '🇹🇷',
      country: 'Turkey (TRT)',
      searchTerms: [
        'turquía',
        'turquia',
        'turkey',
        'estambul',
        'turkish',
        'turco',
        'constantinople',
        'constantinopla',
      ],
    },
    {
      value: 'Europe/Moscow',
      label: 'Moscow',
      flag: '🇷🇺',
      country: 'Russia (MSK)',
      searchTerms: ['rusia', 'russia', 'moscú', 'moscu', 'russian', 'ruso'],
    },
    {
      value: 'Asia/Dubai',
      label: 'Dubai',
      flag: '🇦🇪',
      country: 'UAE (GST)',
      searchTerms: [
        'emiratos árabes',
        'emiratos arabes',
        'united arab emirates',
        'dubái',
        'dubai',
        'uae',
        'abu dhabi',
        'middle east',
        'medio oriente',
      ],
    },
    {
      value: 'Asia/Riyadh',
      label: 'Riyadh',
      flag: '🇸🇦',
      country: 'Saudi Arabia (AST)',
      searchTerms: [
        'arabia saudita',
        'arabia saudí',
        'saudi arabia',
        'riyadh',
        'riad',
        'middle east',
        'medio oriente',
        'arab',
        'árabe',
        'arabe',
      ],
    },
    {
      value: 'Asia/Jerusalem',
      label: 'Jerusalem',
      flag: '🇮🇱',
      country: 'Israel (IST)',
      searchTerms: [
        'israel',
        'jerusalén',
        'jerusalen',
        'tel aviv',
        'israeli',
        'israelí',
        'israeli',
        'middle east',
        'medio oriente',
      ],
    },
    {
      value: 'Asia/Tehran',
      label: 'Tehran',
      flag: '🇮🇷',
      country: 'Iran (IRST)',
      searchTerms: [
        'irán',
        'iran',
        'teherán',
        'tehran',
        'iranian',
        'iraní',
        'irani',
        'persia',
        'persian',
        'middle east',
        'medio oriente',
      ],
    },
    {
      value: 'Asia/Kolkata',
      label: 'Mumbai',
      flag: '🇮🇳',
      country: 'India (IST)',
      searchTerms: [
        'india',
        'bombay',
        'mumbai',
        'delhi',
        'bangalore',
        'chennai',
        'kolkata',
        'calcuta',
        'indian',
        'indio',
        'hindu',
      ],
    },
    {
      value: 'Asia/Karachi',
      label: 'Karachi',
      flag: '🇵🇰',
      country: 'Pakistan (PKT)',
      searchTerms: [
        'pakistán',
        'pakistan',
        'karachi',
        'islamabad',
        'lahore',
        'pakistani',
        'paquistaní',
        'paquistani',
      ],
    },
    {
      value: 'Asia/Dhaka',
      label: 'Dhaka',
      flag: '🇧🇩',
      country: 'Bangladesh (BST)',
      searchTerms: ['bangladesh', 'daca', 'dhaka', 'bangladeshi', 'bengali', 'bengalí', 'bengali'],
    },
    {
      value: 'Asia/Bangkok',
      label: 'Bangkok',
      flag: '🇹🇭',
      country: 'Thailand (ICT)',
      searchTerms: ['tailandia', 'thailand', 'bangkok', 'thai', 'tailandés', 'tailandes', 'siam'],
    },
    {
      value: 'Asia/Singapore',
      label: 'Singapore',
      flag: '🇸🇬',
      country: 'Singapore (SGT)',
      searchTerms: ['singapur', 'singapore', 'singaporean'],
    },
    {
      value: 'Asia/Jakarta',
      label: 'Jakarta',
      flag: '🇮🇩',
      country: 'Indonesia (WIB)',
      searchTerms: ['indonesia', 'yakarta', 'jakarta', 'bali', 'indonesian', 'indonesio'],
    },
    {
      value: 'Asia/Manila',
      label: 'Manila',
      flag: '🇵🇭',
      country: 'Philippines (PST)',
      searchTerms: ['filipinas', 'philippines', 'manila', 'cebu', 'filipino'],
    },
    {
      value: 'Asia/Ho_Chi_Minh',
      label: 'Ho Chi Minh',
      flag: '🇻🇳',
      country: 'Vietnam (ICT)',
      searchTerms: ['vietnam', 'saigon', 'saigón', 'hanoi', 'vietnamese', 'vietnamita'],
    },
    {
      value: 'Asia/Hong_Kong',
      label: 'Hong Kong',
      flag: '🇭🇰',
      country: 'Hong Kong (HKT)',
      searchTerms: ['hong kong', 'hongkong', 'hk', 'china'],
    },
    {
      value: 'Asia/Shanghai',
      label: 'Shanghai',
      flag: '🇨🇳',
      country: 'China (CST)',
      searchTerms: [
        'china',
        'shanghái',
        'shanghai',
        'beijing',
        'pekín',
        'pekin',
        'chinese',
        'chino',
      ],
    },
    {
      value: 'Asia/Taipei',
      label: 'Taipei',
      flag: '🇹🇼',
      country: 'Taiwan (CST)',
      searchTerms: ['taiwán', 'taiwan', 'taipéi', 'taipei', 'taiwanese', 'formosa'],
    },
    {
      value: 'Asia/Tokyo',
      label: 'Tokyo',
      flag: '🇯🇵',
      country: 'Japan (JST)',
      searchTerms: [
        'japón',
        'japon',
        'japan',
        'tokio',
        'tokyo',
        'osaka',
        'kyoto',
        'japanese',
        'japonés',
        'japones',
        'nippon',
      ],
    },
    {
      value: 'Asia/Seoul',
      label: 'Seoul',
      flag: '🇰🇷',
      country: 'South Korea (KST)',
      searchTerms: [
        'corea del sur',
        'corea',
        'korea',
        'seúl',
        'seoul',
        'busan',
        'korean',
        'coreano',
      ],
    },
    {
      value: 'Australia/Perth',
      label: 'Perth',
      flag: '🇦🇺',
      country: 'Australia (AWST)',
      searchTerms: [
        'australia',
        'perth',
        'western australia',
        'australia occidental',
        'aussie',
        'australiano',
      ],
    },
    {
      value: 'Australia/Sydney',
      label: 'Sydney',
      flag: '🇦🇺',
      country: 'Australia (AEST)',
      searchTerms: [
        'australia',
        'sídney',
        'sidney',
        'sydney',
        'new south wales',
        'aussie',
        'australiano',
      ],
    },
    {
      value: 'Australia/Melbourne',
      label: 'Melbourne',
      flag: '🇦🇺',
      country: 'Australia (AEST)',
      searchTerms: ['australia', 'melbourne', 'victoria', 'aussie', 'australiano'],
    },
    {
      value: 'Pacific/Auckland',
      label: 'Auckland',
      flag: '🇳🇿',
      country: 'New Zealand (NZST)',
      searchTerms: [
        'nueva zelanda',
        'nueva zelandia',
        'new zealand',
        'auckland',
        'wellington',
        'kiwi',
        'neozelandés',
        'neozelandes',
      ],
    },
    {
      value: 'Pacific/Fiji',
      label: 'Fiji',
      flag: '🇫🇯',
      country: 'Fiji (FJT)',
      searchTerms: ['fiyi', 'fiji', 'fijian', 'oceania', 'oceanía', 'pacific', 'pacifico'],
    },
    {
      value: 'Africa/Cairo',
      label: 'Cairo',
      flag: '🇪🇬',
      country: 'Egypt (EET)',
      searchTerms: ['egipto', 'egypt', 'el cairo', 'cairo', 'egyptian', 'egipcio'],
    },
    {
      value: 'Africa/Johannesburg',
      label: 'Johannesburg',
      flag: '🇿🇦',
      country: 'South Africa (SAST)',
      searchTerms: [
        'sudáfrica',
        'sudafrica',
        'south africa',
        'johannesburg',
        'johannesburgo',
        'cape town',
        'ciudad del cabo',
        'pretoria',
        'durban',
      ],
    },
    {
      value: 'Africa/Lagos',
      label: 'Lagos',
      flag: '🇳🇬',
      country: 'Nigeria (WAT)',
      searchTerms: ['nigeria', 'lagos', 'abuja', 'nigerian', 'nigeriano'],
    },
    {
      value: 'Africa/Nairobi',
      label: 'Nairobi',
      flag: '🇰🇪',
      country: 'Kenya (EAT)',
      searchTerms: ['kenia', 'kenya', 'nairobi', 'kenyan', 'keniano'],
    },
  ]

  const convertTime = (time: string, fromTz: string, toTz: string): string => {
    if (!time || !fromTz || !toTz) return ''

    try {
      const parts = time.split(':')
      const parsedHours = Number(parts[0])
      const parsedMinutes = Number(parts[1] ?? 0)
      const hours = Number.isFinite(parsedHours) ? parsedHours : 0
      const minutes = Number.isFinite(parsedMinutes) ? parsedMinutes : 0
      const today = new Date()
      const date = new Date(today.getFullYear(), today.getMonth(), today.getDate(), hours, minutes)

      const formatter = new Intl.DateTimeFormat('en-US', {
        timeZone: fromTz,
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      })

      const localTimeString = formatter.format(date)
      const localParts = localTimeString.split(':')
      const parsedLocalHours = Number(localParts[0])
      const localHours = Number.isFinite(parsedLocalHours) ? parsedLocalHours : 0
      const diff = hours - localHours

      const utcDate = new Date(date)
      utcDate.setHours(utcDate.getHours() + diff)

      const resultFormatter = new Intl.DateTimeFormat('en-US', {
        timeZone: toTz,
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      })

      return resultFormatter.format(utcDate)
    } catch {
      return 'Error'
    }
  }

  return {
    timezones,
    convertTime,
  }
}
